using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MotionDetectorWebApi.Controllers.Communication;
using MotionDetectorWebApi.Services;

namespace MotionDetectorWebApi.Controllers
{
    /// <summary>
    /// Web Push API
    /// </summary>
    [Route("api/webpush")]
    public class WebPushController : Controller
    {
        private readonly IWebPushService _webPushService;

        public WebPushController(IWebPushService webPushService)
        {
            _webPushService = webPushService;
        }

        /// <summary>
        /// Get vapid keys
        /// </summary>
        /// <returns>Vapid keys generated by server</returns>
        [Route("vapid")]
        [HttpGet]
        public IActionResult Get()
        {
            var vapid = _webPushService.GetVapidDetails(1);
            return new JsonResult(vapid);
        }

        /// <summary>
        /// Subscribe
        /// </summary>
        /// <remarks>Create subscription for Web Push messages</remarks>
        /// <param name="subscriptionRequest"></param>
        /// <returns>HTTP 200 if subscription created successfull</returns>
        [Route("subscriptions")]
        [HttpPost]
        public IActionResult Post([FromBody] PushSubscriptionRequest subscriptionRequest)
        {
            _webPushService.Create(1, subscriptionRequest.Endpoint, subscriptionRequest.P256dh,
                subscriptionRequest.Auth);
            return new OkResult();
        }


        /// <summary>
        /// Create message
        /// </summary>
        /// <remarks>Create new Web Push message. Message will be sent back to subscribed user as a notification.</remarks>
        /// <param name="pushRequest"></param>
        /// <returns>HTTP 200 if subscription created successfull</returns>
        [Route("messages")]
        [HttpPost]
        public async Task<IActionResult> Post([FromBody] PushRequest pushRequest)
        {
            pushRequest.Message = pushRequest.Message;
            var message = await _webPushService.SendNotificationForUser(1, pushRequest.Message);
            return new CreatedResult("", message);
        }
    }
}